#!/usr/bin/env bash

source /etc/AIROCmAL/AIROCmAL_path
aiinaalpkg=Forge

AIROCmAL_update_Forge () {
  cd $AIROCmALdir/$aiinaalpkg
  git fetch --all
  git branch backup-master
  git reset --hard origin/master
  git pull
  rm ./libref-$aiinaalpkg*
  rm ./requirements_$aiinaalpkg*
  wget https://raw.githubusercontent.com/JT-Gresham/AIROCmAL/main/Forge/libref-$aiinaalpkg
  wget https://raw.githubusercontent.com/JT-Gresham/AIROCmAL/main/Forge/user_customize_$aiinaalpkg_example.sh
  wget https://raw.githubusercontent.com/JT-Gresham/AIROCmAL/main/Forge/requirements_$aiinaalpkg.txt
  AIROCmAL update Torch
  pip install -r requirements_$aiinaalpkg.txt
  AIROCmAL update Intel
  if grep -Fxq "import intel_extension_for_pytorch as ipex" webui.py
    then
      echo "Intel extensions found in webui.py...skipping"
    else
      sed -i 's|from modules import timer|import torch\nimport intel_extension_for_pytorch as ipex\nimport intel_extension_for_transformers\n\nfrom modules import timer|g' webui.py
  fi



rm -R "$AIROCmALdir/$aiinaalpkg/models/Stable-diffusion"
rm -R "$AIROCmALdir/$aiinaalpkg/models/Lora"
rm -R "$AIROCmALdir/$aiinaalpkg/extensions/sd-dynamic-prompts/wildcards"
#rm -R "$AIROCmALdir/$aiinaalpkg/sdxl_styles"
rm -R "$AIROCmALdir/$aiinaalpkg/models/VAE"
rm -R "$AIROCmALdir/$aiinaalpkg/models/VAE-approx"
rm -R "$AIROCmALdir/$aiinaalpkg/outputs/txt2img-grids"
rm -R "$AIROCmALdir/$aiinaalpkg/outputs/txt2img-images"
rm -R "$AIROCmALdir/$aiinaalpkg/models/ControlNet"
rm -R "$AIROCmALdir/$aiinaalpkg/models/ControlNetPreprocessor/clip_vision"
ln -sf "$AIROCmALdir/shared/checkpoints/t2i" "$AIROCmALdir/$aiinaalpkg/models/Stable-diffusion"
ln -sf "$AIROCmALdir/shared/loras/t2i" "$AIROCmALdir/$aiinaalpkg/models/Lora"
ln -sf "$AIROCmALdir/shared/wildcards/" "$AIROCmALdir/$aiinaalpkg/extensions/sd-dynamic-prompts/wildcards"
#ln -sf "$AIROCmALdir/shared/sdxl_styles/$aiinaalpkg" "$AIROCmALdir/$aiinaalpkg/sdxl_styles"
ln -sf "$AIROCmALdir/shared/VAEs/t2i/vae/" "$AIROCmALdir/$aiinaalpkg/models/VAE"
ln -sf "$AIROCmALdir/shared/VAEs/t2i/vae_approx/" "$AIROCmALdir/$aiinaalpkg/models/VAE-approx"
ln -sf "$AIROCmALdir/shared/output/txt2img-grids" "$AIROCmALdir/$aiinaalpkg/outputs/txt2img-grids"
ln -sf "$AIROCmALdir/shared/output/" "$AIROCmALdir/$aiinaalpkg/outputs/txt2img-images"
ln -sf "$AIROCmALdir/shared/controlnet/" "$AIROCmALdir/$aiinaalpkg/models/ControlNet"
ln -sf "$AIROCmALdir/shared/clip_vision/" "$AIROCmALdir/$aiinaalpkg/models/ControlNetPreprocessor/clip_vision"

cd $pdirectory
$AIROCmALdir/$aiinaalpkg/user_customize_$aiinaalpkg.sh
cd $AIROCmALdir/$aiinaalpkg
}

Forge-exit () {
    kill $(pidof python $AIROCmALdir/$aiinaalpkg)
}
